#!/bin/sh

USRFL=`mktemp`
GRPFL=`mktemp`
echo 'gaoxiang:137935' > ${USRFL}
echo 'gaoxiang:3000' > ${GRPFL}
OPS="-o follow_symlinks,idmap=file,nomap=ignore,uidfile=${USRFL},gidfile=${GRPFL}"
sshfs qasdfgtyuiop@nanohub.org: ~/mnt/hipergator/home ${OPS}
rm -rf ${USRFL} ${GRPFL}
